from DB.creation.db_creation import db_connection
from UI.error import error_popup


def insert_admin(admin_data):

    connection = db_connection()

    cursor = connection.cursor()
    cursor.execute("USE autogenerated_blood_donation;")

    # admin_data = [
    #     ('dhanesh',1234, 'Pbks2023Cup'),
    #     ('karthi',5678, 'K@rth1rOcks')
    # ]

    admin_data_insert_query = """
        INSERT INTO admin (admin_name, admin_id, password)
        VALUES (           %s        ,%s       ,%s);
    """

    cursor.executemany(admin_data_insert_query,admin_data)
    connection.commit()

    error_popup("Admin data inserted successfully!")

    cursor.close()
    connection.close()