from DB.db_connection import db_connection

def insert_admin():

    connection = db_connection()

    cursor = connection.cursor()
    cursor.execute("USE autogenerated_blood_donation;")

    admin_data = [
        ('dhanesh',1234, 'Pbks2023Cup'),
        ('karthi',5678, 'K@rth1rOcks')
    ]

    admin_data_insert_query = """
        INSERT INTO admin (admin_name, admin_id, password)
        VALUES (           %s        ,%s       ,%s);
    """

    cursor.executemany(admin_data_insert_query,admin_data)
    connection.commit()

    print("Admin data inserted successfully!")

    cursor.close()
    connection.close()