import mysql.connector

## insert in hospital table first lol

database_name = 'autogenerated_blood_donation'

# Connect to the MySQL database
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Yh1pwth@t",
    # database=database_name
)

# Create a cursor object to execute SQL queries
cursor = conn.cursor()

cursor.execute("USE autogenerated_blood_donation;")


donor_data = [
  (123456789012, 'Male', 'John', 'Doe', 1990,1,1,'A+', False, False, '123 Main St', 'Mumbai', 'Mumbai Suburban', 'Maharashtra', 'India', '+91', 'P@ssw0rd', 'Doe', 'Jane', 'Jon Cornor', 9876543210, 9876543210, 1)
]

# Define the query string with placeholders
qonor_data_insert_query = """
 INSERT INTO donor (aadhaar_id, gender, first_name, lname_name, dob,mob,yob, blood_type, pregnancy_status, HIV, street_name, city, district, state, country, country_code, password, father_name, mother_name, gaurdian_name, ph1, ph2, hid) 
 VALUES (           %s        , %s    , %s        ,%s         ,%s  ,%s ,%s ,%s         ,%s               ,%s  ,%s          ,%s   ,%s       ,%s    ,%s      , %s          , %s      , %s         , %s         ,%s            ,%s  ,%s  ,%s);
 """

cursor.executemany(qonor_data_insert_query,donor_data)

conn.commit()


print("Donor data inserted successfully!")

# Close the cursor and the connection
cursor.close()
conn.close()