import mysql.connector

## insertt in hospital table first lol

database_name = 'autogenerated_blood_donation'

# Connect to the MySQL database
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Yh1pwth@t",
    # database=database_name
)

# Create a cursor object to execute SQL queries
cursor = conn.cursor()

cursor.execute("USE autogenerated_blood_donation;")

hospital_data = [
    (1, 'Hospital 1', 'Password1@', 400, 50, 1234567890, 'Street 1', 'City 1', 'District 1', 'State 1', 'Country 1',  2, 7, 9, 13,   37, 23, 32, 10,   50, 50, 50, 50,   50, 50, 50, 50),
]

hospital_data_insert_query = """
    INSERT INTO hospital (hid, hname, password, total_capacity, quantity_required, contact_no, street_name, city, district, state, country, o_plus_available, a_plus_available, b_plus_available, ab_plus_available, o_minus_available, a_minus_available, b_minus_available, ab_minus_available, o_plus_maximum, a_plus_maximum, b_plus_maximum, ab_plus_maximum, o_minus_maximum, a_minus_maximum, b_minus_maximum, ab_minus_maximum)
    VALUES (              %s ,%s    ,%s       ,%s             ,%s                ,%s         ,%s          ,%s   ,%s       ,%s    ,%s      ,%s               ,%s               ,%s               ,%s                ,%s               ,%s                 ,%s                ,%s                 ,%s             ,%s             ,%s             ,%s              ,%s              ,%s              ,%s              ,%s);
"""

cursor.executemany(hospital_data_insert_query,hospital_data)

conn.commit()


donor_data = [
  (123456789012, 'Male', 'John', 'Doe', 1990,1,1,'A+', False, False, '123 Main St', 'Mumbai', 'Mumbai Suburban', 'Maharashtra', 'India', '+91', 'P@ssw0rd', 'Doe', 'Jane', 'Jon Cornor', 9876543210, 9876543210, 1)
]

# Define the query string with placeholders
qonor_data_insert_query = """
 INSERT INTO donor (aadhaar_id, gender, first_name, lname_name, dob,mob,yob, blood_type, pregnancy_status, HIV, street_name, city, district, state, country, country_code, password, father_name, mother_name, gaurdian_name, ph1, ph2, hid) 
 VALUES (           %s        , %s    , %s        ,%s         ,%s  ,%s ,%s ,%s         ,%s               ,%s  ,%s          ,%s   ,%s       ,%s    ,%s      , %s          , %s      , %s         , %s         ,%s            ,%s  ,%s  ,%s);
 """

cursor.executemany(qonor_data_insert_query,donor_data)

conn.commit()


admin_data = [
    ('dhanesh',1234, 'Pbks2023Cup'),
    ('karthi',5678, 'K@rth1rOcks')
]

admin_data_insert_query = """
    INSERT INTO admin (admin_name, admin_id, password)
    VALUES (           %s        ,%s       ,%s);
"""

cursor.executemany(admin_data_insert_query,admin_data)

conn.commit()

print("Data inserted successfully!")

# Close the cursor and the connection
cursor.close()
conn.close()