import mysql.connector

def db_creation_connection():
    # database_name = 'autogenerated_blood_donation'

    # Connect to the MySQL database
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="Yh1pwth@t",
        # database=database_name
    )

    # Create a cursor object to execute SQL queries
    
    return connection

def db_connection():
    database_name = 'autogenerated_blood_donation'

    # Connect to the MySQL database
    connection = mysql.connector.connect(
        host="localhost",
        user="root",
        password="Yh1pwth@t",
        database=database_name
    )

    # Create a cursor object to execute SQL queries
    
    return connection